### ISSUE TITLE
The footer link CSS becomes dark in dark mode.

### ISSUE THREAD

**Issue by hoanguyenn2015** [a-chacon/wind#1]
Hi there, I just installed your repo and have a problem at footer CSS.

The footer link CSS use light color at dark theme.
The text `Wind` at `Copyright © 2024 Wind` in your demo

.hover\:text-gray-800:hover {
  --tw-text-opacity: 1;
  color: rgb(31 41 55/var(--tw-text-opacity))
}

**Comment by a-chacon** [comment]
Hello! Oh, I didn't notice that. I'll fix it soon, and your suggestion sounds great! Thank you!
