### ISSUE TITLE
Possibly wrong font name

### ISSUE THREAD

**Issue by hoanguyenn2015** [a-chacon/wind#2]
In style.css there are Prata and Adamina fonts, I think it should be `font-family: 'Adamina';` as in the asset file. But why I test `Adamina` it looks the same.

`@font-face {
  font-family: 'Prata';
  src: url('/assets/Adamina/Adamina-Regular.ttf') format('woff2');
  font-display: swap;
}

@layer base {
  html {
    font-family: Prata, system-ui, sans-serif;
  }
}`

**Comment by a-chacon** [comment]
It could be wrong, I changed the font in the way. If you want you can send me a PR fixing this. I will be happy to review and aprove it.

**Comment by a-chacon** [comment]
This was fixed in: https://github.com/a-chacon/wind/pull/4
