### ISSUE TITLE
Middle column shifted 

### ISSUE THREAD

**Issue by katrin-yoga-classes** [a-chacon/wind#5]
Hey there! 

Thank you so much for sharing your Jekyll template. I started to use it, and I am wondering whether you could help me figure out why the middle column on the landing page is slightly shifted, and does not start at the same height as the other two columns? 

Best wishes & many thanks in advance!
Katrin

**Comment by a-chacon** [comment]
Hello @katrin-yoga-classes! You are welcome. 

Did you modify the template? I mean, I am looking your site and I see just two columns, that is strange. I will review it later and give you more details. In the meantime, if you have more details, it will be very helpful.

**Comment by katrin-yoga-classes** [comment]
Hi & thanks for the fast reply! 

I am playing around with the site, but I haven't modified the template. The site should have 3 columns again. It has something to do with the images, sometimes all 3 columns start at the same height, and one post (+image) commit further, the middle column is shifted again. 

For today I leave it as it is, 3 columns, shifted top, so you can have a look. 

Many thanks!
Katrin

**Comment by katrin-yoga-classes** [comment]
Good morning! 

Perhaps it is just a style decision, so I think, you could close the issue, up to you. 

I stopped looking into it for the moment. 

Best wishes & many thanks again, 
Katrin

**Comment by a-chacon** [comment]
Hey! Good morning. I am sorry, I didn't have time to see it. I am in a full-time job and another projects too. And if this is not a problem, then I will close the issue. Good bye!
